import Link from "next/link";
import type { Metadata } from "next";
import { LogoMark } from "@/components/LogoMark";

export const metadata: Metadata = { title: "Terms of Service — Milestoned" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-navy text-fg">
      <div className="mx-auto max-w-[720px] px-6 py-14">
        <Link href="/" className="mb-10 flex items-center gap-[11px]">
          <LogoMark />
          <span className="font-display text-lg font-semibold tracking-[-0.01em] text-fg-bright">
            Milestoned
          </span>
        </Link>

        <h1 className="mb-2 font-display text-3xl font-semibold tracking-[-0.02em] text-fg-heading">
          Terms of Service
        </h1>
        <p className="mb-10 text-sm text-fg-muted">Last updated: July 2026</p>

        <div className="mb-8 rounded-[10px] border border-gold-border bg-gold-soft px-4 py-3.5 text-sm leading-[1.6] text-fg-label">
          This is a plain-language starting point, not a substitute for legal advice. Have it
          reviewed by a lawyer before you rely on it commercially.
        </div>

        <Section title="What Milestoned is">
          <p>
            Milestoned helps you draft client documents — Scopes of Work, Contracts,
            Proposals, and Invoices. Credits are spent to generate a document; unused credits
            don&apos;t expire.
          </p>
        </Section>

        <Section title="Not legal advice">
          <p>
            Documents generated by Milestoned are a drafting aid, not legal advice. They
            haven&apos;t been reviewed by a licensed attorney. For cross-border engagements
            or higher-value contracts, have your generated documents reviewed by a qualified
            lawyer before relying on them.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            You&apos;re responsible for the accuracy of what you enter into the generator and
            for keeping your account credentials secure. You own the documents you generate.
          </p>
        </Section>

        <Section title="Billing">
          <p>
            Credit packages are purchased through Stripe. Purchased credits are non-refundable
            once spent on generating a document, but unused credits carry no expiry.
          </p>
        </Section>

        <Section title="Founding pricing">
          <p>
            If you sign up before launch, the founding price you locked in for credit
            packages remains yours for as long as you keep your account, even after standard
            pricing changes for new signups.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            We may update these terms as the product evolves. Material changes will be
            communicated by email.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms:{" "}
            <span className="text-fg-label">collab@duodevlogs.com</span>.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="mb-2.5 font-display text-lg font-semibold tracking-[-0.01em] text-fg-heading">
        {title}
      </h2>
      <div className="text-[14.5px] leading-[1.65] text-fg-secondary">{children}</div>
    </div>
  );
}
